"""Post-process an autogenerated Alembic migration so `use_alter=True` foreign keys are created
with explicit `op.create_foreign_key` after all tables exist (SQLAlchemy omits them from
CREATE TABLE inside `op.create_table`). Usage: python scripts/fix_circular_fks.py <migration.py>
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

PATTERN = re.compile(
    r"[ \t]*sa\.ForeignKeyConstraint\(\s*\[['\"](?P<col>\w+)['\"]\],\s*\[['\"](?P<ref>\w+)\.id['\"]\],\s*"
    r"name=['\"](?P<name>fk_\w+)['\"],\s*ondelete=['\"]SET NULL['\"],\s*use_alter=True,?\s*\),\n"
)
TABLE_RE = re.compile(r"op\.create_table\(\s*['\"](?P<table>\w+)['\"],")


def main(path: Path) -> None:
    src = path.read_text()
    fks: list[tuple[str, str, str, str]] = []
    # find which table each constraint belongs to by scanning create_table blocks in order
    out: list[str] = []
    pos = 0
    for m in PATTERN.finditer(src):
        table_match = None
        for t in TABLE_RE.finditer(src, 0, m.start()):
            table_match = t
        assert table_match is not None
        fks.append((m.group("name"), table_match.group("table"), m.group("ref"), m.group("col")))
        out.append(src[pos : m.start()])
        pos = m.end()
    out.append(src[pos:])
    src = "".join(out)
    if not fks:
        print("no circular FKs found")
        return
    add = "\n    # Circular references are added after both tables exist.\n" + "".join(
        f'    op.create_foreign_key("{name}", "{table}", "{ref}", ["{col}"], ["id"], ondelete="SET NULL")\n'
        for name, table, ref, col in fks
    )
    drop = "".join(
        f'    op.drop_constraint("{name}", "{table}", type_="foreignkey")\n' for name, table, ref, col in fks
    )
    src = src.replace("\n\ndef downgrade() -> None:\n", add + "\n\ndef downgrade() -> None:\n" + drop, 1)
    src = src.replace("    # ### commands auto generated by Alembic - please adjust! ###\n", "").replace(
        "    # ### end Alembic commands ###\n", ""
    )
    path.write_text(src)
    print(f"rewrote {len(fks)} circular FKs in {path.name}")


if __name__ == "__main__":
    main(Path(sys.argv[1]))
